//! Модульный набор `.cfg`: `config/<категория>.cfg`, при необходимости `binds` / `buy_binds`, `autoexec.cfg`.

use std::collections::HashMap;

use chrono::Local;

use crate::cfg_config::CfgConfig;
use crate::data::aliases::generate_aliases_cfg;
use crate::data::cvars::CvarsCatalog;
use crate::generator::{categorize_settings, console_banner, fmt_cvar_line, CAT_ORDER};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ModularFile {
    pub relative_path: String,
    pub content: String,
}

/// Собрать набор относительных путей и содержимого для записи в папку `cstrike/` или аналог.
pub fn generate_modular_files(cfg: &CfgConfig) -> Result<Vec<ModularFile>, String> {
    let catalog = CvarsCatalog::global();
    let categorized = categorize_settings(catalog, &cfg.settings);
    let now = Local::now().format("%Y-%m-%d %H:%M").to_string();
    let mut files: Vec<ModularFile> = Vec::new();
    let mut exec_lines: Vec<String> = Vec::new();

    let aliases_content = generate_aliases_cfg(cfg)?;
    if !aliases_content.is_empty() {
        files.push(ModularFile {
            relative_path: "config/aliases.cfg".into(),
            content: aliases_content,
        });
        exec_lines.push("exec config/aliases.cfg".into());
    }

    let category_labels: HashMap<&str, &str> = [
        ("video", "VIDEO"),
        ("audio", "AUDIO"),
        ("input", "MOUSE / INPUT"),
        ("network", "NETWORK"),
        ("gameplay", "GAMEPLAY / HUD"),
        ("demo", "DEMO"),
        ("other", "OTHER"),
    ]
    .into_iter()
    .collect();

    for cat_key in CAT_ORDER.iter() {
        let cat_settings = match categorized.get(*cat_key) {
            Some(s) if !s.is_empty() => s,
            _ => continue,
        };
        let label = category_labels
            .get(cat_key)
            .map(|s| (*s).to_string())
            .unwrap_or_else(|| (*cat_key).to_uppercase());
        let rel = format!("config/{cat_key}.cfg");
        let mut lines: Vec<String> = Vec::new();
        lines.push(format!("// Generated by GoldSrc Config Engineer — {}", rel));
        lines.push(format!("// {now}"));
        lines.push(format!("// === {label} ==="));
        for (cvar, value) in cat_settings {
            lines.push(fmt_cvar_line(catalog, cvar, value, 40));
        }
        files.push(ModularFile {
            relative_path: rel.clone(),
            content: lines.join("\n"),
        });
        exec_lines.push(format!("exec {rel}"));
    }

    let mut extra: Vec<_> = categorized
        .keys()
        .filter(|k| !CAT_ORDER.contains(&k.as_str()))
        .cloned()
        .collect();
    extra.sort();
    for cat_key in &extra {
        let cat_settings = &categorized[cat_key];
        if cat_settings.is_empty() {
            continue;
        }
        let rel = format!("config/{cat_key}.cfg");
        let mut lines: Vec<String> = Vec::new();
        lines.push(format!("// Generated — {rel}"));
        lines.push(format!("// {now}"));
        lines.push(format!("// === {} ===", cat_key.to_uppercase()));
        for (cvar, value) in cat_settings {
            lines.push(fmt_cvar_line(catalog, cvar, value, 40));
        }
        files.push(ModularFile {
            relative_path: rel.clone(),
            content: lines.join("\n"),
        });
        exec_lines.push(format!("exec {rel}"));
    }

    if !cfg.binds.is_empty() {
        let mut lines = vec![
            "// config/binds.cfg — generated binds".to_string(),
            format!("// {now}"),
            "// === BINDS ===".to_string(),
        ];
        let mut keys: Vec<_> = cfg.binds.keys().cloned().collect();
        keys.sort();
        for key in keys {
            let cmd = &cfg.binds[&key];
            lines.push(format!(r#"bind "{key}" "{cmd}""#));
        }
        files.push(ModularFile {
            relative_path: "config/binds.cfg".into(),
            content: lines.join("\n"),
        });
        exec_lines.push("exec config/binds.cfg".into());
    }

    let buyscripts_content = crate::data::buyscripts::generate_buyscripts_cfg()?;
    files.push(ModularFile {
        relative_path: "config/buyscripts.cfg".into(),
        content: buyscripts_content,
    });
    exec_lines.push("exec config/buyscripts.cfg".into());

    if !cfg.buy_binds.is_empty() {
        let mut lines = vec![
            "// config/buy_binds.cfg".to_string(),
            format!("// {now}"),
            "// === BUY BINDS ===".to_string(),
        ];
        let mut keys: Vec<_> = cfg.buy_binds.keys().cloned().collect();
        keys.sort();
        for key in keys {
            let cmd = &cfg.buy_binds[&key];
            lines.push(format!(r#"bind "{key}" "{cmd}""#));
        }
        files.push(ModularFile {
            relative_path: "config/buy_binds.cfg".into(),
            content: lines.join("\n"),
        });
        exec_lines.push("exec config/buy_binds.cfg".into());
    }

    let mut auto: Vec<String> = Vec::new();
    auto.push("// ================================================================".into());
    auto.push("// GoldSrc Config Engineer — autoexec.cfg (modular)".into());
    if let Some(ref m) = cfg.mode {
        auto.push(format!("// Mode: {m}"));
    }
    if let Some(ref p) = cfg.preset_name {
        auto.push(format!("// Preset: {p}"));
    }
    auto.push(format!("// Date: {now}"));
    auto.push("// ================================================================".into());
    auto.push(String::new());
    auto.extend(console_banner(cfg));
    auto.push(String::new());
    auto.push("// Modular pieces".into());
    for line in exec_lines {
        auto.push(line);
    }

    files.push(ModularFile {
        relative_path: "autoexec.cfg".into(),
        content: auto.join("\n"),
    });

    Ok(files)
}

#[cfg(test)]
mod tests {
    use crate::cfg_config::CfgConfig;

    use super::generate_modular_files;

    #[test]
    fn modular_set_includes_buyscripts_cfg() {
        let cfg = CfgConfig::default();
        let files = generate_modular_files(&cfg).expect("modular");
        assert!(
            files.iter().any(|f| f.relative_path == "config/buyscripts.cfg"),
            "buyscripts.cfg missing"
        );
    }

    #[test]
    fn autoexec_chains_buyscripts() {
        let cfg = CfgConfig::default();
        let files = generate_modular_files(&cfg).expect("modular");
        let auto = files
            .iter()
            .find(|f| f.relative_path == "autoexec.cfg")
            .expect("autoexec");
        assert!(
            auto.content.contains("buyscripts.cfg"),
            "autoexec should exec buyscripts.cfg"
        );
    }
}
